name: Tests

on:
  push:
    branches:
      - main
    paths:
      - "*.yml"
      - ".github/workflows/*.yml"
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main
    paths:
      - "*.yml"
      - ".github/workflows/*.yml"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install generate-local-changelog
        uses: ./
